### ISSUE TITLE
能否只显示歌名不显示歌手？

### ISSUE THREAD

**Issue by Olvi73** [Leecason/netease-music-box#8]
![image](https://user-images.githubusercontent.com/46037012/101849471-b1d93c00-3b92-11eb-87b7-c99b2479ddab.png)
歌手名字太长导致无法完整显示播放次数

**Comment by Leecason** [comment]
可以去自己 fork 的仓库里修改源码哈

**Comment by Olvi73** [comment]
index.js中的``let name = `${cur.song.name} - ${artists.join('/')}`;``
改成
``let name = `${cur.song.name};` ``
已解决
